# Case Study #04 - Hypothesis Testing
    A company started to invest in digital marketing as a new way of their product promotions.For that they collected data and decided to carry out a study on it.
    ● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.
    ● The company needs to check whether there is any dependency between the features “Region” and “Manager”. 
    
    Help the company to carry out their study with the help of data provided.

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [34]:
#Reading the data set
data = pd.read_csv('Sales_add.csv')
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

### Analysis

In [35]:
#primary analysis on the data set
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [36]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

###  1. The company wishes to clarify whether there is any increase in sales after stepping into digital marketing. 

In [37]:
t_value, p_value = stats.ttest_ind(data['Sales_After_digital_add(in $)'], data['Sales_before_digital_add(in $)'], alternative='greater')
print('p_value is :', p_value)

p_value is : 1.3071840034523225e-16


#### Summary:
    ● P_value is much smaller than the 0.05 (alpha value)
    ● There is an Increase in sales after the stepping into digital marketing

### 2. The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [38]:
#crosstab
contigency= pd.crosstab(data['Region'], data['Manager'])
contigency

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [39]:
x2, x2_p_value, degrees_of_freedom, exp_value = stats.chi2_contingency(contigency)

In [40]:
#Output values
print("The expected values are:\n", exp_value)
print("Degrees of freedom:", degrees_of_freedom)
print("chi square Test statistic:", x2)
print("p-value for the chi square test statistic:", x2_p_value)

The expected values are:
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Degrees of freedom: 4
chi square Test statistic: 3.050566893424036
p-value for the chi square test statistic: 0.5493991051158094


#### Summary:
    ● Since p_value is higher than 0.05 (alpha) we conclude that we accept the Null hypothesis.
    ● That means,there is no dependency between the features "Region" and "Manager".